Avatar Features
FiniteReality/disccord pull request #29
Opened 2017-04-24 12:47 UTC by sedruk

A few feature additions related to avatars:

- [ ] configure avatar data to be read in from stream when user wants to update their avatar

current usage:
```cpp
//file_stream comes included from disccord/rest/api_client.hpp
//using unsigned char stream bcuz the base64 conversion method takes a std::vector<unsigned char>
auto image_stream = file_stream<unsigned char>::open_istream("path/to/file.jpg").get();
modify_current_user_args args;
args.set_avatar(image_stream);
```
current thoughts:
- if we decide to go w/ cpprestsdk's stream lib, might be good to typedef `file_stream<unsigned char>`
- want to play with this impl a little bit

- [ ] add a method to `models::user` that gets the avatar URL pre-built based on hash and user id.
```cpp
//something like this
auto usr = client.get_current_user().get();
client.create_message(<chan_id>,usr.get_avatar_url());
```

(possibly any more, if they come to mind, will be added here too)

2017-04-24 21:47 UTC, sedruk commented
@FiniteReality here are some quick impl's, any input?

2017-04-25 13:50 UTC, FiniteReality requested changes
Most of the changes look good to me, though I'd prefer it if the avatar_url was not pre-constructed on model decode. There are reasons for this, which I'll demonstrate after I merge the PR.

2017-04-25 13:50 UTC, FiniteReality commented on include/disccord/models/user.hpp
> +                util::optional<std::string> avatar, email, avatar_url;
Instead of declaring a new field, define `get_avatar_url`

2017-04-25 13:50 UTC, FiniteReality commented on lib/models/user.cpp
> +            if (get_avatar().is_specified())
Likewise, should use a method to create a url instead

2017-04-25 13:50 UTC, FiniteReality commented on lib/rest/models/modify_current_user_args.cpp
> +                avatar_stream.close();
Do not close the stream the user passes in, it is not our responsibility.

2017-04-25 15:50 UTC, FiniteReality approved these changes

2017-04-25 15:50 UTC, merged