[REST] URL Encoder and Routes
FiniteReality/disccord pull request #36
Opened 2017-07-21 23:03 UTC by sedruk

This is adding a `util::url_encode` method for all reaction-related endpoints. 
Now users can just use codepoints, "U\XXXXXXXX",  or the unicode emoji itself to use these endpoints.
Also, a few routes needed a touch up.

**NOTE:** this has been tested to work with the following cases:
1. "U\XXXXXXXX" - **codepoints**
2. "✅" - **unicode emoji itself**
3. "disccord_memes:1234567891012313" - **custom emojis**

Only does not work when user sends in the percent encoding themselves, (e.g. "%EA%B4%FF"). But this is a desired abstraction.

### Example Usage in the Library (Encoding the URL)
```cpp
// these methods are used when generating the reaction-related routes.
util::url_encode("\U00002705"); //output: %E2%9C%85 (White Heavy Check Mark)
util::url_encode("✅");         //output: %E2%9C%85 (White Heavy Check Mark)
util::url_encode("\U0001F914"); //output: %F0%9F%A4%94 (Thinking Face)
util::url_encode("\U00002B50"); //output: %E2%AD%90 (White Medium Star)
```

### Example Usage for a User (Message Reacting)
```cpp
// sending a message then auto reacting w/ heavy check mark

uint64_t c_id = 1234567891011;
create_message_args cm_args("wow disccord is such an amazing lib!");
auto msg = client.create_message(c_id, cm_args).get();

// using codepoints
client.create_reaction(msg.get_channel_id(), msg.get_id(), "\U00002705").wait();

// or using actual emoji
client.create_reaction(msg.get_channel_id(), msg.get_id(), "✅").wait();
```

2017-07-21 23:09 UTC, sedruk commented
@FiniteReality good2go

2017-07-22 14:41 UTC, FiniteReality requested changes

2017-07-22 14:41 UTC, FiniteReality commented on lib/rest/api_client.cpp
> +                auto route = get_route("PUT", "/channels/{channel.id}/messages/{message.id}/reactions/"+util::url_encode(emoji)+"/@me", std::to_string(channel_id), std::to_string(message_id));
This didn't really need to change much, did it? Just wrap the original emoji parameter in `util::url_encode`?

2017-07-22 14:41 UTC, FiniteReality commented on lib/rest/api_client.cpp
> +                auto route = get_route("DELETE", "/channels/{channel.id}/messages/{message.id}/reactions/"+util::url_encode(emoji)+"/@me", std::to_string(channel_id), std::to_string(message_id));
Likewise, just wrap the original parameter

2017-07-22 14:41 UTC, FiniteReality commented on lib/rest/api_client.cpp
> +                auto route = get_route("DELETE", "/channels/{channel.id}/messages/{message.id}/reactions/"+util::url_encode(emoji)+"/{user.id}", std::to_string(channel_id), std::to_string(message_id)
Here too, just wrap the emoji parameter.

2017-07-22 21:15 UTC, sedruk commented on lib/rest/api_client.cpp
> +                auto route = get_route("PUT", "/channels/{channel.id}/messages/{message.id}/reactions/"+util::url_encode(emoji)+"/@me", std::to_string(channel_id), std::to_string(message_id));
see #30 for why i needed to do it like this for now.

2017-07-22 21:15 UTC, sedruk commented on lib/rest/api_client.cpp
> +                auto route = get_route("DELETE", "/channels/{channel.id}/messages/{message.id}/reactions/"+util::url_encode(emoji)+"/@me", std::to_string(channel_id), std::to_string(message_id));
#30

2017-07-22 21:15 UTC, sedruk commented on lib/rest/api_client.cpp
> +                auto route = get_route("DELETE", "/channels/{channel.id}/messages/{message.id}/reactions/"+util::url_encode(emoji)+"/{user.id}", std::to_string(channel_id), std::to_string(message_id)
#30

2017-07-23 02:23 UTC, sedruk commented
since routing and stuff changed in feature/websocket, i'm making a new PR for `url_encode` for that branch instead, closing this now.

2017-07-23 02:23 UTC, closed without merging